// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package kigen

const (
	Version     = "v0.9.0"
	GitCommit   = "81f4889"          // the commit JUST BEFORE the release
	VersionDate = "2022-02-14 04:58" // UTC
)
