// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package kigen

const (
	Version     = "v1.0.0"
	GitCommit   = "2c4cd0d"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-01 09:34" // UTC
)
