// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package kigen

const (
	Version     = "v1.0.1"
	GitCommit   = "120ea2a"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-07 01:10" // UTC
)
